services:
  postgres:
    container_name: vacancy_management_db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: vacancy_management
    volumes:
      - postgres_data:/bitnami/postgresql

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

volumes:
  postgres_data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
