spring.application.name=vacancy_management
spring.datasource.url=jdbc:postgresql://localhost:5432/vacancy_management
spring.datasource.username=docker
spring.datasource.password=docker
spring.jpa.hibernate.ddl-auto=update


security.token.secret=JAVAVAGAS#02587
security.token.secret.candidate=JAVAVAGAS#02587#CANDIDATE

token.sonarqube=sqp_2a9d0ae9e5f3fb3081aec2ce423abf6a4c6e15e8

management.endpoints.access.default=unrestricted
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.access=read-only
management.endpoint.health.show-details=always
management.endpoint.metrics.access=read-only
management.endpoint.prometheus.access=read-only