spring.application.name=vacancy_management

#   DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# TOKEN
security.token.secret=${JWT_TOKEN}
security.token.secret.candidate=${JWT_TOKEN_CANDIDATE}

token.sonarqube=${SONAR_TOKEN}

management.endpoints.access.default=unrestricted
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.access=read-only
management.endpoint.health.show-details=always
management.endpoint.metrics.access=read-only
management.endpoint.prometheus.access=read-only